### ISSUE TITLE
"Not allowed to load local resource: file:///login"

### ISSUE THREAD

**Issue by linguamachina** [SkelatorIndy/electron-application#3]
From the commit history I can see you recently moved the HTML files into the `views` folder. Perhaps this is the cause of your errors? I still haven't had the chance to pull this down and test, but you might like to try updating the paths in the `render()` calls in `app/routes.js` (e.g change `res.render('login.html', { message: req.flash('loginMessage') });` to `res.render('../views/login.html', { message: req.flash('loginMessage') });` etc).

**Comment by SkelatorIndy** [comment]
The html files have always been in the views folder for my project. Me moving them into the views folder in github was just me accidentally uploading them outside of it. I still changed it to ../views/login.html, but it's just returning the error "cannot find module 'html'"

**Comment by linguamachina** [comment]
OK, something else must be awry then. Sorry, I'm gonna have to get some sleep, but I'll try to pick this up and help out when I next have some free time!

**Comment by SkelatorIndy** [comment]
Ok thank you

**Comment by SkelatorIndy** [comment]
I figured it out. I just had to make a new engine call so that it could read the html files. Thanks for all your help
